name: Deploy Back (Production)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Talented.io
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TALENTEED_HOST }}
          username: ${{ secrets.SSH_TALENTEED_USERNAME }}
          password: ${{ secrets.SSH_TALENTEED_PASSWORD }}
          port: ${{ secrets.SSH_TALENTEED_PORT }}
          script: |
            cd /home/talenteedio/sites/Talenteed-Back/
            ./scripts/deploy_prod.sh
